---
# =============================================================================
# Test camera for creation of images.
# =============================================================================
height: 128
width: 128

K: [64, 0.0, 64, 0.0, 64, 64, 0.0, 0.0, 1.0]
near: 0.001
far: 3.0
camera_position: [0,0.0,1.5]
target_position: [0,0.0,0]
up_direction: [0,1,0]
...
