---
# =============================================================================
# Test camera for creation of images.
# =============================================================================
height: 64
width: 64

K: [32, 0.0, 32, 0.0, 32, 32, 0.0, 0.0, 1.0]
near: 0.001
far: 3.0
camera_position: [0,0.0,1.5]
target_position: [0,0.0,0]
up_direction: [0,1,0]
...
