---
# =============================================================================
# Test camera for creation of images.
# =============================================================================
height: 480
width: 640

K: [333.58709627983416, 0.0, 317.9736055493302, 0.0, 320, 240, 0.0, 0.0, 1.0]
near: 0.001
far: 10
camera_position: [0,0,1.5]
target_position: [0,0,0]
up_direction: [0,1,0]
...
