---
# =============================================================================
# Test camera for creation of images.
# =============================================================================
height: 16
width: 16

K: [8, 0.0, 8, 0.0, 8, 8, 0.0, 0.0, 1.0]
near: 0.001
far: 3.0
camera_position: [0,0.0,1.5]
target_position: [0,0.0,0]
up_direction: [0,1,0]
...
