---
# =============================================================================
# Test camera for creation of images.
# =============================================================================
height: 120
width: 160

K: [83.39675, 0.0, 79.4935, 0.0, 80, 60, 0.0, 0.0, 1.0]
near: 0.001
far: 10
camera_position: [0,0,1.5]
target_position: [0,0,0]
up_direction: [0,1,0]
...
