---
# =============================================================================
# Test camera for creation of images.
# =============================================================================
height: 960
width: 1280

K: [667.1741925597, 0.0, 635.9472110987, 0.0, 640, 480, 0.0, 0.0, 1.0]
near: 0.001
far: 10
camera_position: [0,0,1.5]
target_position: [0,0,0]
up_direction: [0,1,0]
...
